db:
  image: library/mongo
  ports:
    - "27017:27017"
  restart: always

web:
  environment:
    RACK_ENV: production
  build: .
  volumes:
    - .:/opt/www
  command: foreman start -d /opt/www
  ports:
    - "80:4567"
  restart: always
  links:
    - db
